/**
 * Curated stock universe for screening - S&P 500 + Nasdaq 100 + Russell 1000
 * ~500 tickers - performance constrained, not all US equities
 */

export interface UniverseStock {
  ticker: string;
  companyName: string;
  sector: string;
  marketCapTier: "mega" | "large" | "mid";
}

export const UNIVERSE: UniverseStock[] = [
  // Mega Cap Tech
  { ticker: "AAPL", companyName: "Apple Inc", sector: "Technology", marketCapTier: "mega" },
  { ticker: "MSFT", companyName: "Microsoft Corporation", sector: "Technology", marketCapTier: "mega" },
  { ticker: "GOOGL", companyName: "Alphabet Inc Class A", sector: "Technology", marketCapTier: "mega" },
  { ticker: "GOOG", companyName: "Alphabet Inc Class C", sector: "Technology", marketCapTier: "mega" },
  { ticker: "AMZN", companyName: "Amazon.com Inc", sector: "Consumer Cyclical", marketCapTier: "mega" },
  { ticker: "NVDA", companyName: "NVIDIA Corporation", sector: "Technology", marketCapTier: "mega" },
  { ticker: "META", companyName: "Meta Platforms Inc", sector: "Technology", marketCapTier: "mega" },
  { ticker: "TSLA", companyName: "Tesla Inc", sector: "Consumer Cyclical", marketCapTier: "mega" },
  { ticker: "BRK-B", companyName: "Berkshire Hathaway Inc Class B", sector: "Financial Services", marketCapTier: "mega" },
  { ticker: "JPM", companyName: "JPMorgan Chase & Co", sector: "Financial Services", marketCapTier: "mega" },
  { ticker: "V", companyName: "Visa Inc Class A", sector: "Financial Services", marketCapTier: "mega" },
  { ticker: "UNH", companyName: "UnitedHealth Group Inc", sector: "Healthcare", marketCapTier: "mega" },
  { ticker: "JNJ", companyName: "Johnson & Johnson", sector: "Healthcare", marketCapTier: "mega" },
  { ticker: "WMT", companyName: "Walmart Inc", sector: "Consumer Defensive", marketCapTier: "mega" },
  { ticker: "PG", companyName: "Procter & Gamble Co", sector: "Consumer Defensive", marketCapTier: "mega" },
  { ticker: "XOM", companyName: "Exxon Mobil Corporation", sector: "Energy", marketCapTier: "mega" },
  { ticker: "HD", companyName: "Home Depot Inc", sector: "Consumer Cyclical", marketCapTier: "mega" },
  { ticker: "MA", companyName: "Mastercard Inc Class A", sector: "Financial Services", marketCapTier: "mega" },
  { ticker: "CVX", companyName: "Chevron Corporation", sector: "Energy", marketCapTier: "mega" },
  { ticker: "ABBV", companyName: "AbbVie Inc", sector: "Healthcare", marketCapTier: "mega" },
  { ticker: "MRK", companyName: "Merck & Co Inc", sector: "Healthcare", marketCapTier: "mega" },
  { ticker: "PEP", companyName: "PepsiCo Inc", sector: "Consumer Defensive", marketCapTier: "mega" },
  { ticker: "KO", companyName: "Coca-Cola Co", sector: "Consumer Defensive", marketCapTier: "mega" },
  { ticker: "COST", companyName: "Costco Wholesale Corporation", sector: "Consumer Defensive", marketCapTier: "mega" },
  { ticker: "AVGO", companyName: "Broadcom Inc", sector: "Technology", marketCapTier: "mega" },
  { ticker: "LLY", companyName: "Eli Lilly and Co", sector: "Healthcare", marketCapTier: "mega" },
  { ticker: "ORCL", companyName: "Oracle Corporation", sector: "Technology", marketCapTier: "mega" },
  { ticker: "MCD", companyName: "McDonald's Corp", sector: "Consumer Cyclical", marketCapTier: "mega" },
  { ticker: "DIS", companyName: "Walt Disney Co", sector: "Communication Services", marketCapTier: "mega" },
  { ticker: "NEE", companyName: "NextEra Energy Inc", sector: "Utilities", marketCapTier: "mega" },
  // Large Cap Tech
  { ticker: "ADBE", companyName: "Adobe Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "CRM", companyName: "Salesforce Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "CSCO", companyName: "Cisco Systems Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "INTC", companyName: "Intel Corporation", sector: "Technology", marketCapTier: "large" },
  { ticker: "AMD", companyName: "Advanced Micro Devices Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "QCOM", companyName: "Qualcomm Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "TXN", companyName: "Texas Instruments Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "IBM", companyName: "International Business Machines Corp", sector: "Technology", marketCapTier: "large" },
  { ticker: "NOW", companyName: "ServiceNow Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "INTU", companyName: "Intuit Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "AMAT", companyName: "Applied Materials Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "MU", companyName: "Micron Technology Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "LRCX", companyName: "Lam Research Corp", sector: "Technology", marketCapTier: "large" },
  { ticker: "SNPS", companyName: "Synopsys Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "CDNS", companyName: "Cadence Design Systems Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "KLAC", companyName: "KLA Corp", sector: "Technology", marketCapTier: "large" },
  { ticker: "PANW", companyName: "Palo Alto Networks Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "CRWD", companyName: "CrowdStrike Holdings Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "FTNT", companyName: "Fortinet Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "NET", companyName: "Cloudflare Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "DDOG", companyName: "Datadog Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "SNOW", companyName: "Snowflake Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "PLTR", companyName: "Palantir Technologies Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "SHOP", companyName: "Shopify Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "SQ", companyName: "Block Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "PYPL", companyName: "PayPal Holdings Inc", sector: "Financial Services", marketCapTier: "large" },
  { ticker: "UBER", companyName: "Uber Technologies Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "ABNB", companyName: "Airbnb Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "NFLX", companyName: "Netflix Inc", sector: "Communication Services", marketCapTier: "large" },
  { ticker: "SPOT", companyName: "Spotify Technology SA", sector: "Communication Services", marketCapTier: "large" },
  // Financials
  { ticker: "BAC", companyName: "Bank of America Corp", sector: "Financial Services", marketCapTier: "large" },
  { ticker: "WFC", companyName: "Wells Fargo & Company", sector: "Financial Services", marketCapTier: "large" },
  { ticker: "GS", companyName: "Goldman Sachs Group Inc", sector: "Financial Services", marketCapTier: "large" },
  { ticker: "MS", companyName: "Morgan Stanley", sector: "Financial Services", marketCapTier: "large" },
  { ticker: "C", companyName: "Citigroup Inc", sector: "Financial Services", marketCapTier: "large" },
  { ticker: "BLK", companyName: "BlackRock Inc", sector: "Financial Services", marketCapTier: "large" },
  { ticker: "SCHW", companyName: "Charles Schwab Corp", sector: "Financial Services", marketCapTier: "large" },
  { ticker: "AXP", companyName: "American Express Company", sector: "Financial Services", marketCapTier: "large" },
  { ticker: "SPGI", companyName: "S&P Global Inc", sector: "Financial Services", marketCapTier: "large" },
  { ticker: "CME", companyName: "CME Group Inc", sector: "Financial Services", marketCapTier: "large" },
  // Healthcare
  { ticker: "PFE", companyName: "Pfizer Inc", sector: "Healthcare", marketCapTier: "large" },
  { ticker: "TMO", companyName: "Thermo Fisher Scientific Inc", sector: "Healthcare", marketCapTier: "large" },
  { ticker: "ABT", companyName: "Abbott Laboratories", sector: "Healthcare", marketCapTier: "large" },
  { ticker: "DHR", companyName: "Danaher Corporation", sector: "Healthcare", marketCapTier: "large" },
  { ticker: "BMY", companyName: "Bristol-Myers Squibb Co", sector: "Healthcare", marketCapTier: "large" },
  { ticker: "AMGN", companyName: "Amgen Inc", sector: "Healthcare", marketCapTier: "large" },
  { ticker: "GILD", companyName: "Gilead Sciences Inc", sector: "Healthcare", marketCapTier: "large" },
  { ticker: "VRTX", companyName: "Vertex Pharmaceuticals Inc", sector: "Healthcare", marketCapTier: "large" },
  { ticker: "REGN", companyName: "Regeneron Pharmaceuticals Inc", sector: "Healthcare", marketCapTier: "large" },
  { ticker: "MDT", companyName: "Medtronic PLC", sector: "Healthcare", marketCapTier: "large" },
  { ticker: "ISRG", companyName: "Intuitive Surgical Inc", sector: "Healthcare", marketCapTier: "large" },
  { ticker: "ELV", companyName: "Elevance Health Inc", sector: "Healthcare", marketCapTier: "large" },
  { ticker: "CI", companyName: "Cigna Group", sector: "Healthcare", marketCapTier: "large" },
  { ticker: "HUM", companyName: "Humana Inc", sector: "Healthcare", marketCapTier: "large" },
  { ticker: "ZTS", companyName: "Zoetis Inc", sector: "Healthcare", marketCapTier: "large" },
  // Consumer
  { ticker: "NKE", companyName: "Nike Inc Class B", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "SBUX", companyName: "Starbucks Corporation", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "TGT", companyName: "Target Corporation", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "LOW", companyName: "Lowe's Companies Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "BKNG", companyName: "Booking Holdings Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "MAR", companyName: "Marriott International Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "CMG", companyName: "Chipotle Mexican Grill Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "ORLY", companyName: "O'Reilly Automotive Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "AZO", companyName: "AutoZone Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "ROST", companyName: "Ross Stores Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "TJX", companyName: "TJX Companies Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "HD", companyName: "Home Depot Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "PG", companyName: "Procter & Gamble Co", sector: "Consumer Defensive", marketCapTier: "large" },
  { ticker: "PM", companyName: "Philip Morris International Inc", sector: "Consumer Defensive", marketCapTier: "large" },
  { ticker: "MO", companyName: "Altria Group Inc", sector: "Consumer Defensive", marketCapTier: "large" },
  { ticker: "CL", companyName: "Colgate-Palmolive Company", sector: "Consumer Defensive", marketCapTier: "large" },
  { ticker: "KMB", companyName: "Kimberly-Clark Corporation", sector: "Consumer Defensive", marketCapTier: "large" },
  { ticker: "GIS", companyName: "General Mills Inc", sector: "Consumer Defensive", marketCapTier: "large" },
  { ticker: "K", companyName: "Kellanova", sector: "Consumer Defensive", marketCapTier: "large" },
  { ticker: "MDLZ", companyName: "Mondelez International Inc", sector: "Consumer Defensive", marketCapTier: "large" },
  // Industrials
  { ticker: "CAT", companyName: "Caterpillar Inc", sector: "Industrials", marketCapTier: "large" },
  { ticker: "DE", companyName: "Deere & Company", sector: "Industrials", marketCapTier: "large" },
  { ticker: "BA", companyName: "Boeing Co", sector: "Industrials", marketCapTier: "large" },
  { ticker: "HON", companyName: "Honeywell International Inc", sector: "Industrials", marketCapTier: "large" },
  { ticker: "UPS", companyName: "United Parcel Service Inc", sector: "Industrials", marketCapTier: "large" },
  { ticker: "RTX", companyName: "RTX Corp", sector: "Industrials", marketCapTier: "large" },
  { ticker: "LMT", companyName: "Lockheed Martin Corporation", sector: "Industrials", marketCapTier: "large" },
  { ticker: "GE", companyName: "General Electric Company", sector: "Industrials", marketCapTier: "large" },
  { ticker: "UNP", companyName: "Union Pacific Corporation", sector: "Industrials", marketCapTier: "large" },
  { ticker: "FDX", companyName: "FedEx Corporation", sector: "Industrials", marketCapTier: "large" },
  { ticker: "MMM", companyName: "3M Company", sector: "Industrials", marketCapTier: "large" },
  { ticker: "EMR", companyName: "Emerson Electric Co", sector: "Industrials", marketCapTier: "large" },
  { ticker: "ITW", companyName: "Illinois Tool Works Inc", sector: "Industrials", marketCapTier: "large" },
  { ticker: "ETN", companyName: "Eaton Corporation PLC", sector: "Industrials", marketCapTier: "large" },
  { ticker: "WM", companyName: "Waste Management Inc", sector: "Industrials", marketCapTier: "large" },
  // Energy
  { ticker: "COP", companyName: "ConocoPhillips", sector: "Energy", marketCapTier: "large" },
  { ticker: "SLB", companyName: "Schlumberger Ltd", sector: "Energy", marketCapTier: "large" },
  { ticker: "EOG", companyName: "EOG Resources Inc", sector: "Energy", marketCapTier: "large" },
  { ticker: "MPC", companyName: "Marathon Petroleum Corp", sector: "Energy", marketCapTier: "large" },
  { ticker: "PSX", companyName: "Phillips 66", sector: "Energy", marketCapTier: "large" },
  { ticker: "VLO", companyName: "Valero Energy Corporation", sector: "Energy", marketCapTier: "large" },
  { ticker: "OXY", companyName: "Occidental Petroleum Corporation", sector: "Energy", marketCapTier: "large" },
  { ticker: "PXD", companyName: "Pioneer Natural Resources Co", sector: "Energy", marketCapTier: "large" },
  { ticker: "HES", companyName: "Hess Corporation", sector: "Energy", marketCapTier: "large" },
  { ticker: "DVN", companyName: "Devon Energy Corporation", sector: "Energy", marketCapTier: "large" },
  // Communication
  { ticker: "GOOG", companyName: "Alphabet Inc Class C", sector: "Communication Services", marketCapTier: "large" },
  { ticker: "NFLX", companyName: "Netflix Inc", sector: "Communication Services", marketCapTier: "large" },
  { ticker: "CMCSA", companyName: "Comcast Corporation", sector: "Communication Services", marketCapTier: "large" },
  { ticker: "T", companyName: "AT&T Inc", sector: "Communication Services", marketCapTier: "large" },
  { ticker: "VZ", companyName: "Verizon Communications Inc", sector: "Communication Services", marketCapTier: "large" },
  { ticker: "TMUS", companyName: "T-Mobile US Inc", sector: "Communication Services", marketCapTier: "large" },
  { ticker: "CHTR", companyName: "Charter Communications Inc", sector: "Communication Services", marketCapTier: "large" },
  { ticker: "EA", companyName: "Electronic Arts Inc", sector: "Communication Services", marketCapTier: "large" },
  { ticker: "TTWO", companyName: "Take-Two Interactive Software Inc", sector: "Communication Services", marketCapTier: "large" },
  { ticker: "WBD", companyName: "Warner Bros Discovery Inc", sector: "Communication Services", marketCapTier: "large" },
  // Real Estate
  { ticker: "PLD", companyName: "Prologis Inc", sector: "Real Estate", marketCapTier: "large" },
  { ticker: "AMT", companyName: "American Tower Corp", sector: "Real Estate", marketCapTier: "large" },
  { ticker: "EQIX", companyName: "Equinix Inc", sector: "Real Estate", marketCapTier: "large" },
  { ticker: "PSA", companyName: "Public Storage", sector: "Real Estate", marketCapTier: "large" },
  { ticker: "WELL", companyName: "Welltower Inc", sector: "Real Estate", marketCapTier: "large" },
  { ticker: "O", companyName: "Realty Income Corporation", sector: "Real Estate", marketCapTier: "large" },
  { ticker: "DLR", companyName: "Digital Realty Trust Inc", sector: "Real Estate", marketCapTier: "large" },
  { ticker: "SPG", companyName: "Simon Property Group Inc", sector: "Real Estate", marketCapTier: "large" },
  // Utilities
  { ticker: "DUK", companyName: "Duke Energy Corporation", sector: "Utilities", marketCapTier: "large" },
  { ticker: "SO", companyName: "Southern Company", sector: "Utilities", marketCapTier: "large" },
  { ticker: "D", companyName: "Dominion Energy Inc", sector: "Utilities", marketCapTier: "large" },
  { ticker: "AEP", companyName: "American Electric Power Company Inc", sector: "Utilities", marketCapTier: "large" },
  { ticker: "XEL", companyName: "Xcel Energy Inc", sector: "Utilities", marketCapTier: "large" },
  { ticker: "EXC", companyName: "Exelon Corporation", sector: "Utilities", marketCapTier: "large" },
  { ticker: "SRE", companyName: "Sempra Energy", sector: "Utilities", marketCapTier: "large" },
  { ticker: "WEC", companyName: "WEC Energy Group Inc", sector: "Utilities", marketCapTier: "large" },
  { ticker: "ED", companyName: "Consolidated Edison Inc", sector: "Utilities", marketCapTier: "large" },
  { ticker: "AWK", companyName: "American Water Works Company Inc", sector: "Utilities", marketCapTier: "large" },
  // Materials
  { ticker: "LIN", companyName: "Linde PLC", sector: "Basic Materials", marketCapTier: "large" },
  { ticker: "APD", companyName: "Air Products and Chemicals Inc", sector: "Basic Materials", marketCapTier: "large" },
  { ticker: "SHW", companyName: "Sherwin-Williams Company", sector: "Basic Materials", marketCapTier: "large" },
  { ticker: "ECL", companyName: "Ecolab Inc", sector: "Basic Materials", marketCapTier: "large" },
  { ticker: "FCX", companyName: "Freeport-McMoRan Inc", sector: "Basic Materials", marketCapTier: "large" },
  { ticker: "NEM", companyName: "Newmont Corporation", sector: "Basic Materials", marketCapTier: "large" },
  { ticker: "NUE", companyName: "Nucor Corporation", sector: "Basic Materials", marketCapTier: "large" },
  { ticker: "VMC", companyName: "Vulcan Materials Company", sector: "Basic Materials", marketCapTier: "large" },
  { ticker: "DD", companyName: "DuPont de Nemours Inc", sector: "Basic Materials", marketCapTier: "large" },
  { ticker: "DOW", companyName: "Dow Inc", sector: "Basic Materials", marketCapTier: "large" },
  // Additional Russell 1000 / S&P 500
  { ticker: "SPY", companyName: "SPDR S&P 500 ETF Trust", sector: "ETF", marketCapTier: "mega" },
  { ticker: "QQQ", companyName: "Invesco QQQ Trust", sector: "ETF", marketCapTier: "mega" },
  { ticker: "ZM", companyName: "Zoom Video Communications Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "DOCU", companyName: "DocuSign Inc", sector: "Technology", marketCapTier: "mid" },
  { ticker: "MELI", companyName: "MercadoLibre Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "LULU", companyName: "Lululemon Athletica Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "COIN", companyName: "Coinbase Global Inc", sector: "Financial Services", marketCapTier: "large" },
  { ticker: "RBLX", companyName: "Roblox Corporation", sector: "Communication Services", marketCapTier: "large" },
  { ticker: "DKNG", companyName: "DraftKings Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "ROKU", companyName: "Roku Inc", sector: "Communication Services", marketCapTier: "mid" },
  { ticker: "TTD", companyName: "The Trade Desk Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "OKTA", companyName: "Okta Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "ZS", companyName: "Zscaler Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "MDB", companyName: "MongoDB Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "TEAM", companyName: "Atlassian Corporation", sector: "Technology", marketCapTier: "large" },
  { ticker: "WDAY", companyName: "Workday Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "ADSK", companyName: "Autodesk Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "ANSS", companyName: "ANSYS Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "NXPI", companyName: "NXP Semiconductors NV", sector: "Technology", marketCapTier: "large" },
  { ticker: "ASML", companyName: "ASML Holding NV", sector: "Technology", marketCapTier: "large" },
  { ticker: "AVGO", companyName: "Broadcom Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "MRVL", companyName: "Marvell Technology Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "ON", companyName: "ON Semiconductor Corp", sector: "Technology", marketCapTier: "large" },
  { ticker: "MCHP", companyName: "Microchip Technology Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "ADI", companyName: "Analog Devices Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "LAM", companyName: "Lam Research Corp", sector: "Technology", marketCapTier: "large" },
  { ticker: "APH", companyName: "Amphenol Corporation", sector: "Technology", marketCapTier: "large" },
  { ticker: "GLW", companyName: "Corning Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "HPQ", companyName: "HP Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "DELL", companyName: "Dell Technologies Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "HPE", companyName: "Hewlett Packard Enterprise Co", sector: "Technology", marketCapTier: "large" },
  { ticker: "NTAP", companyName: "NetApp Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "AKAM", companyName: "Akamai Technologies Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "FFIV", companyName: "F5 Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "VRSN", companyName: "VeriSign Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "CDW", companyName: "CDW Corporation", sector: "Technology", marketCapTier: "large" },
  { ticker: "KEYS", companyName: "Keysight Technologies Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "HII", companyName: "Huntington Ingalls Industries Inc", sector: "Industrials", marketCapTier: "large" },
  { ticker: "GD", companyName: "General Dynamics Corporation", sector: "Industrials", marketCapTier: "large" },
  { ticker: "NOC", companyName: "Northrop Grumman Corporation", sector: "Industrials", marketCapTier: "large" },
  { ticker: "TDG", companyName: "TransDigm Group Incorporated", sector: "Industrials", marketCapTier: "large" },
  { ticker: "CARR", companyName: "Carrier Global Corporation", sector: "Industrials", marketCapTier: "large" },
  { ticker: "OTIS", companyName: "Otis Worldwide Corporation", sector: "Industrials", marketCapTier: "large" },
  { ticker: "JCI", companyName: "Johnson Controls International PLC", sector: "Industrials", marketCapTier: "large" },
  { ticker: "PH", companyName: "Parker-Hannifin Corporation", sector: "Industrials", marketCapTier: "large" },
  { ticker: "ROK", companyName: "Rockwell Automation Inc", sector: "Industrials", marketCapTier: "large" },
  { ticker: "TT", companyName: "Trane Technologies PLC", sector: "Industrials", marketCapTier: "large" },
  { ticker: "CINF", companyName: "Cincinnati Financial Corporation", sector: "Financial Services", marketCapTier: "large" },
  { ticker: "AFL", companyName: "Aflac Incorporated", sector: "Financial Services", marketCapTier: "large" },
  { ticker: "TRV", companyName: "Travelers Companies Inc", sector: "Financial Services", marketCapTier: "large" },
  { ticker: "ALL", companyName: "Allstate Corporation", sector: "Financial Services", marketCapTier: "large" },
  { ticker: "PGR", companyName: "Progressive Corporation", sector: "Financial Services", marketCapTier: "large" },
  { ticker: "MET", companyName: "MetLife Inc", sector: "Financial Services", marketCapTier: "large" },
  { ticker: "PRU", companyName: "Prudential Financial Inc", sector: "Financial Services", marketCapTier: "large" },
  { ticker: "AIG", companyName: "American International Group Inc", sector: "Financial Services", marketCapTier: "large" },
  { ticker: "CB", companyName: "Chubb Limited", sector: "Financial Services", marketCapTier: "large" },
  { ticker: "MMC", companyName: "Marsh & McLennan Companies Inc", sector: "Financial Services", marketCapTier: "large" },
  { ticker: "ICE", companyName: "Intercontinental Exchange Inc", sector: "Financial Services", marketCapTier: "large" },
  { ticker: "MCO", companyName: "Moody's Corporation", sector: "Financial Services", marketCapTier: "large" },
  { ticker: "FIS", companyName: "Fidelity National Information Services Inc", sector: "Financial Services", marketCapTier: "large" },
  { ticker: "FISV", companyName: "Fiserv Inc", sector: "Financial Services", marketCapTier: "large" },
  { ticker: "GPN", companyName: "Global Payments Inc", sector: "Financial Services", marketCapTier: "large" },
  { ticker: "ADP", companyName: "Automatic Data Processing Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "PAYX", companyName: "Paychex Inc", sector: "Technology", marketCapTier: "large" },
  { ticker: "CTAS", companyName: "Cintas Corporation", sector: "Industrials", marketCapTier: "large" },
  { ticker: "FAST", companyName: "Fastenal Company", sector: "Industrials", marketCapTier: "large" },
  { ticker: "RSG", companyName: "Republic Services Inc", sector: "Industrials", marketCapTier: "large" },
  { ticker: "PCAR", companyName: "PACCAR Inc", sector: "Industrials", marketCapTier: "large" },
  { ticker: "ODFL", companyName: "Old Dominion Freight Line Inc", sector: "Industrials", marketCapTier: "large" },
  { ticker: "CSX", companyName: "CSX Corporation", sector: "Industrials", marketCapTier: "large" },
  { ticker: "NSC", companyName: "Norfolk Southern Corporation", sector: "Industrials", marketCapTier: "large" },
  { ticker: "JBHT", companyName: "J.B. Hunt Transport Services Inc", sector: "Industrials", marketCapTier: "large" },
  { ticker: "CHRW", companyName: "C.H. Robinson Worldwide Inc", sector: "Industrials", marketCapTier: "large" },
  { ticker: "EXPD", companyName: "Expeditors International of Washington Inc", sector: "Industrials", marketCapTier: "large" },
  { ticker: "HAS", companyName: "Hasbro Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "WYNN", companyName: "Wynn Resorts Limited", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "MGM", companyName: "MGM Resorts International", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "LVS", companyName: "Las Vegas Sands Corp", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "HLT", companyName: "Hilton Worldwide Holdings Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "H", companyName: "Hyatt Hotels Corporation", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "CCL", companyName: "Carnival Corporation", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "RCL", companyName: "Royal Caribbean Cruises Ltd", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "NCLH", companyName: "Norwegian Cruise Line Holdings Ltd", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "DHI", companyName: "D.R. Horton Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "LEN", companyName: "Lennar Corporation", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "PHM", companyName: "PulteGroup Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "NVR", companyName: "NVR Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "TOL", companyName: "Toll Brothers Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "F", companyName: "Ford Motor Company", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "GM", companyName: "General Motors Company", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "RIVN", companyName: "Rivian Automotive Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "LCID", companyName: "Lucid Group Inc", sector: "Consumer Cyclical", marketCapTier: "mid" },
  { ticker: "APTV", companyName: "Aptiv PLC", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "BWA", companyName: "BorgWarner Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "LEG", companyName: "Leggett & Platt Incorporated", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "WHR", companyName: "Whirlpool Corporation", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "BBY", companyName: "Best Buy Co Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "POOL", companyName: "Pool Corporation", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "ULTA", companyName: "Ulta Beauty Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "YUM", companyName: "Yum! Brands Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "DPZ", companyName: "Domino's Pizza Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "WING", companyName: "Wingstop Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "DRI", companyName: "Darden Restaurants Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "MKC", companyName: "McCormick & Company Incorporated", sector: "Consumer Defensive", marketCapTier: "large" },
  { ticker: "SJM", companyName: "JM Smucker Co", sector: "Consumer Defensive", marketCapTier: "large" },
  { ticker: "HSY", companyName: "Hershey Co", sector: "Consumer Defensive", marketCapTier: "large" },
  { ticker: "KHC", companyName: "Kraft Heinz Company", sector: "Consumer Defensive", marketCapTier: "large" },
  { ticker: "CPB", companyName: "Campbell Soup Company", sector: "Consumer Defensive", marketCapTier: "large" },
  { ticker: "HRL", companyName: "Hormel Foods Corporation", sector: "Consumer Defensive", marketCapTier: "large" },
  { ticker: "TAP", companyName: "Molson Coors Beverage Company", sector: "Consumer Defensive", marketCapTier: "large" },
  { ticker: "STZ", companyName: "Constellation Brands Inc Class A", sector: "Consumer Defensive", marketCapTier: "large" },
  { ticker: "BF-B", companyName: "Brown-Forman Corporation Class B", sector: "Consumer Defensive", marketCapTier: "large" },
  { ticker: "MNST", companyName: "Monster Beverage Corporation", sector: "Consumer Defensive", marketCapTier: "large" },
  { ticker: "KDP", companyName: "Keurig Dr Pepper Inc", sector: "Consumer Defensive", marketCapTier: "large" },
  { ticker: "CELH", companyName: "Celsius Holdings Inc", sector: "Consumer Defensive", marketCapTier: "large" },
  { ticker: "COST", companyName: "Costco Wholesale Corporation", sector: "Consumer Defensive", marketCapTier: "large" },
  { ticker: "KR", companyName: "Kroger Co", sector: "Consumer Defensive", marketCapTier: "large" },
  { ticker: "SYY", companyName: "Sysco Corporation", sector: "Consumer Defensive", marketCapTier: "large" },
  { ticker: "TSCO", companyName: "Tractor Supply Company", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "DG", companyName: "Dollar General Corporation", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "DLTR", companyName: "Dollar Tree Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "BBY", companyName: "Best Buy Co Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "WSM", companyName: "Williams-Sonoma Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "RH", companyName: "RH", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "ETSY", companyName: "Etsy Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "W", companyName: "Wayfair Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "CHWY", companyName: "Chewy Inc", sector: "Consumer Cyclical", marketCapTier: "large" },
  { ticker: "PET", companyName: "Petco Health and Wellness Company Inc", sector: "Consumer Cyclical", marketCapTier: "mid" },
];

// Deduplicate by ticker (some may have been added twice)
const seen = new Set<string>();
export const SCREENING_UNIVERSE = UNIVERSE.filter((s) => {
  if (seen.has(s.ticker)) return false;
  seen.add(s.ticker);
  return true;
});
